spring:
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-name: GitHub
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
  main:
    banner-mode: off
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    date-format: 'yyyy-MM-dd HH:mm:ss'
  application:
    name: co-assemble-api

coassemble:
  admin-email: ${ADMIN_EMAIL:admin@gmail.com}
  admin-password: ${ADMIN_EMAIL:coassemble}
  domain: ${COASSEMBLE_DOMAIN:http://localhost:${server.port}}
  verification-token-ttl: 3m
  mail-link-prefix: ${COASSEMBLE_DOMAIN:http://localhost:${server.port}/api/v1/auth}


logging:
  level:
    kz.danekerscode.coassembleapi: debug
    org.springframework:
      web: debug
      security: debug
server:
  error:
    include-message: always
  port: 8080
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api-docs/swagger-ui.html