name: Build image and push to Docker Hub

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed
    branches:
      - 'master' # todo change to test after creating prod env

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Allow permissions to gradlew
        run: chmod +x gradlew

      - name: Run build
        run: ./gradlew build bootJar

      - name: docker login
        run: echo $DOCKER_PASSWORD | docker login --username daneker --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t daneker/co-assemble-api .

      - name: Push Docker image
        run: docker push daneker/co-assemble-api
  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd coassemble/test
            sudo docker rmi -f daneker/co-assemble-api
            sudo docker compose down -v
            sudo docker compose up -d

