name: Build image and push to Docker Hub

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed
    branches:
      - 'master' # todo change to test after creating prod env

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Allow permissions to gradlew
        run: chmod +x gradlew

      - name: Run build
        run: ./gradlew build bootJar

      - name: docker login
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/co-assemble-api .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/co-assemble-api
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
