name: Build image and push to Docker Hub

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed
    branches:
      - test

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/co-assemble-api .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/co-assemble-api
