name: Build image and push to Docker Hub

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed
    branches:
      - 'test'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Allow permissions to gradlew
        run: chmod +x gradlew

      - name: Run build
        run: ./gradlew build bootJar

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/co-assemble-api .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/co-assemble-api
