name: Create release

# Controls when the action will run
# Option bellow allows you to run the workflow manually
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release new version'
# Allow GitHub Actions to push changes to the repository
permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Allow permissions to gradlew
        run: chmod +x gradlew

      - name: Setup git config
        run: |
          git config user.name {{ secrets.GITHUB_USERNAME }}
          git config user.email {{ secrets.GITHUB_EMAIL }}
      - name: Release with Gradle Release Plugin
        run: ./gradlew release